name: publish-container

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: oom-dcc-arc
    steps:
      - run: sudo apt-get update && sudo apt-get install -y xz-utils ca-certificates
      - run: sudo update-ca-certificates
      - run: ls -l /etc/ssl/certs/ca-certificates.crt
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            ssl-cert-file = /etc/ssl/certs/ca-certificates.crt
            experimental-features = nix-command flakes
            accept-flake-config = true
      - name: Publish Houdini Container
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          NIX_SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
          SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
        run: . /home/runner/.nix-profile/etc/profile.d/nix.sh
        run: nix run .#publish-houdini-container

